#server:
#  port: 8081
#
#spring:
#  application:
#    name: customer-service
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888