server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movie/**, /api/genre/**
          filters:
            - AuthenticationFilter

        - id: cinema-service
          uri: lb://cinema-service
          predicates:
            - Path=/api/cinema/**, /api/hall/**, /api/screening/**, /api/seat/**
          filters:
            - AuthenticationFilter

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        - id: aggregator-service
          uri: lb://aggregator-service
          predicates:
            - Path=/api/aggregator/**
          filters:
            - AuthenticationFilter

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /api/auth/v3/api-docs
      - name: movie-service
        url: /api/movie/v3/api-docs
      - name: cinema-service
        url: /api/cinema/v3/api-docs
      - name: booking-service
        url: /api/booking/v3/api-docs
      - name: payment-service
        url: /api/payment/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        maxAttempts: 3
        initialInterval: 1000
        multiplier: 1.2
        maxInterval: 2000
