server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**, /api/movie/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        maxAttempts: 3
        initialInterval: 1000
        multiplier: 1.2
        maxInterval: 2000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
