server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: native
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customer/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        maxAttempts: 3
        initialInterval: 1000
        multiplier: 1.2
        maxInterval: 2000